<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Storage.Json</PackageId>
    <Description>JSON file-per-entity IRepository provider.</Description>
    <IsPackable>true</IsPackable>
    <RootNamespace>Novolis.Storage.Json</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Novolis.Storage.Unit" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Novolis.IO.Workspace" />
    <ProjectReference Include="../Novolis.Storage.Abstractions/Novolis.Storage.Abstractions.csproj" />
  </ItemGroup>
</Project>
